version: '1.0.{build}'
image: Visual Studio 2019

environment:
  COVERALLS_REPO_TOKEN:
    secure: q6V0pTjMedkIXA/sZTBQB3nApTSGg29BBqFnI6/PbqXS5DmdAhgbbMqIAcf13/I5
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
before_build:
  # Display .NET Core version
  - cmd: choco install codecov
  - cmd: dotnet --version
  - ps: ./tabletop/build.ps1 -target=linux-arm64
artifacts:
 - path: './linux-arm64'
   name: tabletop-linux-arm64
   type: WebDeployPackage
clone_depth: 1
test_script:
  - cmd: codecov -f ./tabletop/tabletop.test/netcore-coverage.cobertura.xml -t $(COVERALLS_REPO_TOKEN)
on_finish :
  # any cleanup in here
deploy: off
