trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      ls
    workingDirectory: 'tabletop'
- task: PowerShell@2
  displayName: 'Cake Powershell'
  inputs:
    targetType: filePath
    filePath: 'tabletop\build.ps1'
    arguments: '-ScriptArgs ''-runtime="linux-arm64"'''
    workingDirectory: 'tabletop'
- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage from $(Build.SourcesDirectory)\tabletop\tabletop.test\netcore-coverage.cobertura.xml'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: 'tabletop\tabletop.test\netcore-coverage.cobertura.xml'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: linux-arm64'
  inputs:
    PathtoPublish: 'tabletop\tabletop-linux-arm64.zip'
    ArtifactName: 'linux-arm64'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: generic-netcore'
  inputs:
    PathtoPublish: 'tabletop\tabletop-generic-netcore.zip'
    ArtifactName: 'tabletop-generic-netcore'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: coverage.report zip'
  inputs:
    PathtoPublish: 'tabletop\tabletop.test\coverage-report.zip'
    ArtifactName: coverage-report
