// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using tabletop.Data;

namespace tabletop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20180125132503_AddLinkDatabase4")]
    partial class AddLinkDatabase4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("tabletop.Models.ChannelEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("NameId")
                        .IsRequired();

                    b.Property<int>("Status");

                    b.Property<int>("Weight");

                    b.HasKey("Id");

                    b.HasIndex("NameId");

                    b.ToTable("ChannelEvent");
                });

            modelBuilder.Entity("tabletop.Models.ChannelUser", b =>
                {
                    b.Property<string>("NameId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80);

                    b.Property<bool>("IsVisible");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.HasKey("NameId");

                    b.ToTable("ChannelUser");
                });

            modelBuilder.Entity("tabletop.Models.ChannelEvent", b =>
                {
                    b.HasOne("tabletop.Models.ChannelUser", "Name")
                        .WithMany("ChannelEvents")
                        .HasForeignKey("NameId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
