// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using tabletop.Data;

namespace tabletop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20180125125834_AddLinkDatabase")]
    partial class AddLinkDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("tabletop.Models.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsVisible");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<string>("NameId")
                        .HasMaxLength(80);

                    b.Property<int?>("UpdateStatusId");

                    b.HasKey("Id");

                    b.HasIndex("UpdateStatusId")
                        .IsUnique()
                        .HasFilter("[UpdateStatusId] IS NOT NULL");

                    b.ToTable("Channel");
                });

            modelBuilder.Entity("tabletop.Models.UpdateStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateTime");

                    b.Property<int>("Status");

                    b.Property<int>("Weight");

                    b.HasKey("Id");

                    b.ToTable("UpdateStatus");
                });

            modelBuilder.Entity("tabletop.Models.Channel", b =>
                {
                    b.HasOne("tabletop.Models.UpdateStatus", "UpdateStatus")
                        .WithOne("Name")
                        .HasForeignKey("tabletop.Models.Channel", "UpdateStatusId");
                });
#pragma warning restore 612, 618
        }
    }
}
