// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tabletop.Data;

namespace tabletop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200419093236_SqliteResetMigrations")]
    partial class SqliteResetMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("tabletop.Models.ChannelEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChannelUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChannelUserId");

                    b.ToTable("ChannelEvent");
                });

            modelBuilder.Entity("tabletop.Models.ChannelUser", b =>
                {
                    b.Property<string>("NameId")
                        .HasColumnType("TEXT")
                        .HasMaxLength(80);

                    b.Property<string>("Bearer")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<bool>("IsAccessible")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(80);

                    b.Property<string>("NameUrlSafe")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(80);

                    b.HasKey("NameId");

                    b.ToTable("ChannelUser");
                });

            modelBuilder.Entity("tabletop.Models.ChannelEvent", b =>
                {
                    b.HasOne("tabletop.Models.ChannelUser", "ChannelUser")
                        .WithMany("ChannelEvents")
                        .HasForeignKey("ChannelUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
